[theme]
# Cor Dourada extraída do Logo (Gold/Mustard)
primaryColor = "#C9A227"

# Fundo "Carbono" (Preto suave, não cansa a vista)
backgroundColor = "#0E1117"

# Sidebar um pouco mais clara para contraste
secondaryBackgroundColor = "#161920"

# Texto Branco (Off-white)
textColor = "#FAFAFA"

# Fonte limpa
font = "sans serif"

[server]
headless = true